### ISSUE TITLE
wishlist -> tensorflow deep convolutional recursive swarm of hybrid bdi and ANN

### ISSUE THREAD

**Issue by ghost** [OSALTDev/WishList#3]
<h1> [WISHLIST] tensorflow deep convolutional recursive swarm of hybrid bdi and ANN</h1>

<b>hey guys, it would be cool, to have:</b>

- <i>an implementation of the previous model in a framework like tensorflow.</i>

<b>just use this: </b>

- <i>https://drive.google.com/file/d/0B2kT6ra3MW4FTnI1OFRtcWdheWs/view?usp=sharing as a basis for start developing it. i will be happy to get involved. </i>

It was my research proposal for applying for **phd at city university of london (studentship)**. i was not accepted, so **i decided to share it with a couple of people, to attempt at implementing seriously at a wider range**. 

i think it's a cool project because it has **medical and musical implications (can even be applied for videogames as well or for anything you may want)**, and **can be used to trace some patterns with some of the health issues that nixie is dealing with**, and potentially **some other disorders**, and stuff.

**Comment by mjeveritt** [comment]
In technical terms .. WTF .. ?!

**Comment by safaci2000** [comment]
it's been a while since this was posted and I just . wanted to circle back.  What is your ask?  Do you want us to host this?  Do you want to collaborate with others in regards to potential uses of it?
